version: '3.4'

services:
  solidsiteprod:
    image: solidsiteprod
    build:
      context: .output/server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
