FROM rust:1.70-bullseye

RUN apt update && \
  apt install -y binaryen npm protobuf-compiler libssl-dev pkg-config musl-tools \
  && rm -rf /var/lib/apt/lists/*

RUN rustup target add wasm32-unknown-unknown
RUN rustup component add clippy

RUN cargo install cargo-generate
RUN cargo install cargo-leptos
RUN cargo install wasm-opt
RUN npm install -g sass

WORKDIR /work

CMD /bin/bash
