FROM rust:1.70-alpine3.18

RUN apk update && \
  apk add --no-cache bash binaryen gcc git g++ libc-dev make npm openssl-dev protobuf-dev protoc curl bash

RUN rustup target add wasm32-unknown-unknown
RUN rustup component add clippy

# RUN cargo install wasm-opt
RUN cargo install cargo-leptos
